// jobTitles.ts

export const jobTitleSections = {
  "Technology": [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Data Analyst",
    "UI/UX Designer",
    "DevOps Engineer",
    "Cybersecurity Analyst",
    "Cloud Architect",
    "Machine Learning Engineer",
    "IT Support Specialist",
    "Systems Analyst",
    "Database Administrator",
    "Mobile App Developer",
    "Quality Assurance Tester",
    "Technical Writer",
    "Network Engineer",
    "Help Desk Technician",
    "Web Developer",
    "Game Developer",
    "IT Project Coordinator",
    "Technical Support Engineer",
    "Scrum Master",
    "Product Manager",
    "Data Scientist",
    "Business Analyst",
    "Penetration Tester",
    "Digital Marketing Specialist",
    "Software Tester",
    "IT Intern",
  ],
  "Business": [
    "Accountant",
    "Financial Analyst",
    "Marketing Manager",
    "Sales Executive",
    "Operations Manager",
    "HR Manager",
    "Business Consultant",
    "Brand Manager",
    "Customer Service Representative",
    "Payroll Specialist",
    "Recruitment Officer",
    "Office Manager",
    "Administrative Assistant",
    "Training and Development Specialist",
    "Budget Analyst",
    "Procurement Officer",
    "Market Research Analyst",
    "Public Relations Officer",
    "Business Development Officer",
    "Quality Assurance Analyst",
    "Retail Store Supervisor",
    "Corporate Communications Officer",
    "E-commerce Manager",
    "Audit Associate",
    "Compliance Officer",
    "Risk Manager",
    "Sales Intern",
    "HR Intern",
  ],
  "Hospitality": [
    "Hotel Manager",
    "Front Desk Officer",
    "Housekeeping Supervisor",
    "Event Coordinator",
    "Food and Beverage Manager",
    "Chef",
    "Pastry Chef",
    "Guest Relations Officer",
    "Travel Consultant",
    "Bartender",
    "Banquet Manager",
    "Catering Coordinator",
    "Concierge",
    "Room Attendant",
    "Restaurant Supervisor",
    "Receptionist",
    "Hotel Reservations Agent",
    "Banquet Server",
    "Event Manager",
    "Kitchen Steward",
    "Restaurant Host",
    "Room Service Attendant",
    "Spa Manager",
    "Facilities Manager",
    "Travel Concierge",
    "Hotel Operations Manager",
    "Hospitality Trainer",
    "Hotel Intern",
    "Event Intern",
    "F&B Intern",
  ],
  "Tourism": [
    "Tourism Officer",
    "Travel Agent",
    "Tour Guide",
    "Cruise Ship Staff",
    "Resort Manager",
    "Event Tour Organizer",
    "Travel Reservation Agent",
    "Tourism Marketing Specialist",
    "Adventure Guide",
    "Travel Blogger",
    "Airport Ground Crew",
    "Ticketing Officer",
    "Visa Consultant",
    "Tour Operator",
    "Tourism Development Officer",
    "Guest Experience Specialist",
    "Tour Logistics Assistant",
    "Travel Content Creator",
    "Eco-Tourism Specialist",
    "Cultural Liaison",
    "Tour Program Coordinator",
    "Inbound Tour Operator",
    "Outbound Tour Operator",
    "Tourism Promotion Officer",
    "Festival Organizer",
    "Theme Park Attendant",
    "Tourism Intern",
    "Travel Intern",
  ],
};

